version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    secrets:
      - db_password

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ConfessIt
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MONGO_INITDB_DATABASE: ConfessDB
    volumes:
      - ./mongo_data:/data/db
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  mongodata:
