version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080", "--strictPort"]
    ports:
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  backend:
    build:
      context: ./backend
    command: [
      "uvicorn",
      "app.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8001",
      "--reload",
      "--reload-dir",
      "app"
    ]
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./archives:/app/archives
    depends_on:
      - redis
    secrets:
      - db_password
    environment:
      WATCHFILES_FORCE_POLLING: "true"
      WATCHFILES_POLL_DELAY: "0.5"
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:7-alpine
    container_name: confessit_redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  redis_data:
