version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080", "--strictPort"]
    ports:
      - "5173:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  backend:
    build:
      context: ./backend
    command: [
      "uvicorn",
      "app.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8001",
      "--reload",
      "--reload-dir",
      "app"
    ]
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    secrets:
      - db_password
    environment:
      WATCHFILES_FORCE_POLLING: "true"
      WATCHFILES_POLL_DELAY: "0.5"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ConfessIt
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MONGO_INITDB_DATABASE: ConfessDB
    volumes:
      - ./mongo_data:/data/db
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  mongodata:
